### ISSUE TITLE
Logr implementation that delegates to testing.T.Log()

### ISSUE THREAD

**Issue by ash2k** [go-logr/stdr#6]
I'm trying to replace a logging framework in a library with the logr abstraction. I'd be very useful to have a logr implementation that writes to [`testing.B.Log()`](https://pkg.go.dev/testing#B.Log) / [`testing.T.Log()`](https://pkg.go.dev/testing#T.Log) like what https://pkg.go.dev/go.uber.org/zap/zaptest package allows to do. I don't want to add a dependency on zap to the library... because I'd like to remove the dependency on a (different) logging framework.

Another useful thing would be a no-op implementation that can be used by default if no concrete implementation was provided. The library uses functional options and hence it'd be nice to make it optional to provide a logger.

**Comment by thockin** [comment]
https://github.com/go-logr/logr/blob/master/testing/test.go

https://github.com/go-logr/logr/blob/master/discard.go
